name: C++ CI

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-22.04  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev

      - name: Build and run tests
        run: |
          make

